# Generated by Django 6.0 on 2025-12-31 19:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('etudiant', 'Visa Étudiant'), ('tourisme', 'Tourisme & Vacances'), ('travail', 'Permis de Travail'), ('medical', 'Évacuation Sanitaire')], max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question fréquente')),
                ('reponse', ckeditor.fields.RichTextField(verbose_name='Réponse détaillée')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Plus le chiffre est petit, plus la question apparaît haut')),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Questions Fréquentes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('niveau_etudes', models.CharField(choices=[('bac', "Diplôme d'État (Bac)"), ('bac_plus_3', 'Graduat / Licence (Bac+3)'), ('bac_plus_5', 'Licence / Master (Bac+5)'), ('doctorat', 'Doctorat'), ('autre', 'Autre / Professionnel')], max_length=20)),
                ('destination', models.CharField(choices=[('canada', 'Canada'), ('france', 'France'), ('belgique', 'Belgique'), ('usa', 'USA'), ('chine', 'Chine'), ('autre', 'Autre')], max_length=20)),
                ('situation_financiere', models.CharField(choices=[('faible', "Je n'ai pas encore de budget"), ('moyen', "J'ai un garant (Famille)"), ('fort', "J'ai mes propres fonds / Compte bloqué")], max_length=20)),
                ('date_simulation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(help_text="Mettre un prénom ou 'Anonyme' pour la confidentialité", max_length=100)),
                ('destination', models.CharField(help_text='Ex: Canada, Dubaï', max_length=100)),
                ('type_temoignage', models.CharField(choices=[('visa', 'Photo de Visa (Preuve)'), ('client', 'Photo Client (Avis)')], default='visa', max_length=20)),
                ('photo', models.ImageField(upload_to='temoignages/')),
                ('message', models.TextField(blank=True, help_text='Le commentaire du client ou une description courte')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du guide')),
                ('destination', models.CharField(help_text='Ex: Canada, Chine, Dubaï', max_length=100)),
                ('image_couverture', models.ImageField(upload_to='guides/covers/')),
                ('contenu', ckeditor.fields.RichTextField(verbose_name='Contenu détaillé du guide')),
                ('est_phare', models.BooleanField(default=False, verbose_name="Mettre à la une sur l'accueil ?")),
                ('slug', models.SlugField(unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='voyage.categorie')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Formulaire de demande', max_length=100)),
                ('fichier', models.FileField(upload_to='guides/docs/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='voyage.guide')),
            ],
        ),
    ]
