# Generated by Django 6.0 on 2025-12-31 19:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(help_text="Nom de l'icone (ex: user-graduate)", max_length=50)),
                ('image_banniere', models.ImageField(upload_to='services/')),
                ('resume_court', models.TextField(help_text="Pour la carte sur l'accueil")),
                ('contenu_complet', ckeditor.fields.RichTextField(help_text='Description détaillée du service')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
