# Generated by Django 6.0 on 2025-12-31 20:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_travelservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la bourse')),
                ('slug', models.SlugField(unique=True)),
                ('pays', models.CharField(max_length=100, verbose_name='Pays de destination')),
                ('niveau', models.CharField(help_text='Ex: Licence, Master, Doctorat', max_length=100)),
                ('couverture', models.CharField(choices=[('totale', 'Totale (Billet + Frais + Vie)'), ('partielle', 'Partielle (Frais de scolarité uniquement)'), ('exemption', 'Exemption de frais majorés')], default='totale', max_length=20)),
                ('date_limite', models.DateField(verbose_name='Date limite de candidature')),
                ('image', models.ImageField(upload_to='bourses/')),
                ('contenu', ckeditor.fields.RichTextField(verbose_name='Détails et Critères')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date_limite'],
            },
        ),
    ]
