# Generated by Django 6.0 on 2026-01-01 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voyage', '0003_bourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon - Incomplet'), ('analyse', "En cours d'analyse"), ('valide', 'Validé - Prêt pour dépôt'), ('refuse', 'À corriger')], default='brouillon', max_length=20)),
                ('pourcentage_completion', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.categorie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('obligatoire', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Ex: Scannez la page avec la photo')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_requis', to='voyage.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='FichierClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='clients/docs/')),
                ('etat', models.CharField(choices=[('attente', 'En attente de vérification'), ('valide', 'Validé par un expert'), ('rejete', 'Rejeté (Illisible/Incorrect)')], default='attente', max_length=20)),
                ('commentaire_admin', models.TextField(blank=True, help_text='Raison du rejet si nécessaire')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='procedure.dossier')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.typedocument')),
            ],
        ),
    ]
