# Generated by Django 6.0 on 2026-01-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='a_deja_voyage',
            field=models.BooleanField(default=False, verbose_name='Avez-vous déjà voyagé ?'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_prevue_voyage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='etape_creation',
            field=models.PositiveIntegerField(default=1, help_text='Étape actuelle du wizard (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='motif_detaille',
            field=models.TextField(blank=True, help_text='Décrivez votre projet en quelques lignes', null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='ville_depart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='ville_destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
