# Generated by Django 6.0 on 2026-01-10 15:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_dossier_a_deja_voyage_dossier_date_prevue_voyage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en USD', max_digits=10)),
                ('credits_inclus', models.PositiveIntegerField(help_text='Nombre de vérifications incluses')),
                ('description', ckeditor.fields.RichTextField(help_text='Liste des avantages (HTML)')),
                ('est_populaire', models.BooleanField(default=False, help_text='Mettre en avant ?')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='credits_restants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossier',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procedure.offre'),
        ),
    ]
