# Generated by Django 6.0 on 2026-01-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_offre_dossier_credits_restants_dossier_date_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='pays_destination',
            field=models.CharField(choices=[('canada', 'Canada'), ('france', 'France'), ('belgique', 'Belgique'), ('usa', 'Etats Unis'), ('finlande', 'Finlande'), ('allemagne', 'Allemagne'), ('swede', 'Swède'), ('australie', 'Australie')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('pays', models.CharField(choices=[('canada', 'Canada'), ('france', 'France'), ('belgique', 'Belgique'), ('usa', 'Etats Unis'), ('finlande', 'Finlande'), ('allemagne', 'Allemagne'), ('swede', 'Swède'), ('australie', 'Australie')], max_length=50)),
                ('site_web', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universites/')),
                ('documents_admission', models.ManyToManyField(blank=True, related_name='universites_requerantes', to='procedure.typedocument')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='universite_choisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='procedure.universite'),
        ),
    ]
